version: "3"
services:
  mongodb-service:
    image: mongo
    volumes:
      - data:/data/db
    container_name: mongodb-service
    ports:
      - 27017:27017

  backend:
    image: 127.0.0.1:6000/backend-app
    container_name: backend
    ports:
      - 5000:5000
    depends_on:
      - mongodb-service

  frontend:
    image: 127.0.0.1:6000/frontend-app
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  data: