version: '3'
services:
  mongodb-service:
    image: mongo
    volumes:
      - data:/data/db
    container_name: mongodb-service
    ports:
      - 27017:27017

  backend:
    image: abdorty/backend-app:back-app-v1
    container_name: backend
    ports:
      - 5000:5000
    depends_on:
      - mongodb-service

  frontend:
    image: abdorty/frontend-app:front-app-v1
    container_name: frontend
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  data:
